# Project information
site_name: shakespearelang
site_url: https://shakespearelang.com
site_author: Zeb Burke-Conte

# Repository
repo_url: https://github.com/zmbc/shakespearelang
repo_name: zmbc/shakespearelang
edit_uri: edit/main/docs/
nav:
  - Getting started: index.md
  - Command line usage reference: CLI.md
  - Python API reference: API.md
theme:
  name: material
  custom_dir: mkdocs_overrides
  palette:
    primary: teal
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: true
            members_order: source
      watch:
        - shakespearelang
extra:
  version:
    provider: mike
markdown_extensions:
  - mkdocs-click
  - toc:
      permalink: "#"
