name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_pyenv:
    runs-on: ubuntu-latest
    name: install pyenv
    steps:
    - name: setup pyenv
      uses: gabrielfalcao/pyenv-action@v7
      with:
        versions: 3.6.12, 3.7.9, 3.8.6, 3.9.1
        command: pip install -U poetry
    - name: Run tox
      run: tox
